/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAave, IAaveInterface } from "../IAave";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "referralCode",
        type: "uint16",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAave__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveInterface {
    return new utils.Interface(_abi) as IAaveInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAave {
    return new Contract(address, _abi, signerOrProvider) as IAave;
  }
}
