/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721securitization,
  IERC721securitizationInterface,
} from "../IERC721securitization";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721securitization__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721securitizationInterface {
    return new utils.Interface(_abi) as IERC721securitizationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721securitization {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721securitization;
  }
}
