/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ICreditVaultInterface extends ethers.utils.Interface {
  functions: {
    "approveOnCreditDelegation(uint256)": FunctionFragment;
    "getPositionAmount(uint256)": FunctionFragment;
    "getPositionCreditor(uint256)": FunctionFragment;
    "returnCollateral(uint256,uint256)": FunctionFragment;
    "saveData(address,address,address,uint256,address,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveOnCreditDelegation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionCreditor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "saveData",
    values: [
      string,
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveOnCreditDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionCreditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saveData", data: BytesLike): Result;

  events: {};
}

export class ICreditVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICreditVaultInterface;

  functions: {
    approveOnCreditDelegation(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPositionAmount(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPositionCreditor(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    returnCollateral(
      _amount: BigNumberish,
      _counter: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    saveData(
      _debitor: string,
      _creditor: string,
      _token: string,
      _amount: BigNumberish,
      _collateral: string,
      _amountCollateral: BigNumberish,
      _month: BigNumberish,
      _year: BigNumberish,
      _interest: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approveOnCreditDelegation(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPositionAmount(
    _counter: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPositionCreditor(
    _counter: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  returnCollateral(
    _amount: BigNumberish,
    _counter: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  saveData(
    _debitor: string,
    _creditor: string,
    _token: string,
    _amount: BigNumberish,
    _collateral: string,
    _amountCollateral: BigNumberish,
    _month: BigNumberish,
    _year: BigNumberish,
    _interest: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveOnCreditDelegation(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPositionAmount(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPositionCreditor(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    returnCollateral(
      _amount: BigNumberish,
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    saveData(
      _debitor: string,
      _creditor: string,
      _token: string,
      _amount: BigNumberish,
      _collateral: string,
      _amountCollateral: BigNumberish,
      _month: BigNumberish,
      _year: BigNumberish,
      _interest: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveOnCreditDelegation(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPositionAmount(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPositionCreditor(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    returnCollateral(
      _amount: BigNumberish,
      _counter: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    saveData(
      _debitor: string,
      _creditor: string,
      _token: string,
      _amount: BigNumberish,
      _collateral: string,
      _amountCollateral: BigNumberish,
      _month: BigNumberish,
      _year: BigNumberish,
      _interest: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveOnCreditDelegation(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPositionAmount(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPositionCreditor(
      _counter: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    returnCollateral(
      _amount: BigNumberish,
      _counter: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    saveData(
      _debitor: string,
      _creditor: string,
      _token: string,
      _amount: BigNumberish,
      _collateral: string,
      _amountCollateral: BigNumberish,
      _month: BigNumberish,
      _year: BigNumberish,
      _interest: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
